// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btiyvtmtyxcaszcvwlwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0aXl2dG10eXhjYXN6Y3Z3bHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDE1NDUsImV4cCI6MjA2NzYxNzU0NX0.43yt4uskBsMwgqtYmBXOiof4ifo2jX-DpEsjmfEuHcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});